spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8  #portfolio 데이터 베이스를 사용
    username: root  #root 계정 사용
    password: Chris9559!  #root 계정의 비밀번호로 작성
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect  #사용하는 DB에 따라 변경
    show-sql: false
    hibernate.ddl-auto: create
    #    create: SessionFactory 시작시 스키마를 삭제하고 다시 생성
    #    create-drop: SessionFactory 종료 시 스키마를 삭제
    #    update: SessionFactory 연결된 DB와 비교하여 추가된 항목은 추가 만약 같은 변수명이면 오류발생
    #    validate: SessionFactory 시작시 객체구성과 스키마가 다르다면 예외 발생
    #    none: 아무것도 안함
